##########
# Presence based
##########

- id: notify_phone_home
  alias: Notify when tony phone changes location
  trigger: 
    platform: state
    entity_id: device_tracker.520dcd99cbb97b7d
  action:
    service: notify.pushover
    data_template:
      title: Tony Nexus 6 Location Changed
      message: >
        {{ trigger.from_state.state }} to {{ trigger.to_state.state }}

- id: living_room_lights_before_sunset
  alias: Turn on living room lights hour before sunset
  trigger: 
    - platform: sun
      event: sunset
      offset: "-01:00:00"
    - platform: state
      entity_id: device_tracker.520dcd99cbb97b7d
      state: 'home'
  condition:
    - condition: state
      entity_id: device_tracker.520dcd99cbb97b7d
      state: 'home'
  action: 
    - service: scene.turn_on
      entity_id: scene.living_room_concentrate

- id: living_room_lights_yellow_at_sunset
  alias: Turn on living room lights when sun sets and home
  trigger: 
    - platform: sun
      event: sunset
      offset: "-00:15:00"
    - platform: state
      entity_id: device_tracker.520dcd99cbb97b7d
      state: 'home'
  condition:
    - condition: state
      entity_id: device_tracker.520dcd99cbb97b7d
      state: 'home'
  action: 
    - service: scene.turn_on
      entity_id: scene.living_room_bright
    
- id: all_lights_off_leave_home
  alias: Turn off all lights when leaving home
  trigger:
    platform: state
    entity_id: device_tracker.520dcd99cbb97b7d
    state: 'not_home'
  condition:
    condition: state
    entity_id: device_tracker.520dcd99cbb97b7d
    state: 'not_home'
  action:
    - delay: 00:05:00
    - service: light.turn_off
      entity_id: group.all_lights

##########
# Time based
##########

# Living Room
- id: living_room_get_relaxed
  alias: Living Room Get Relaxed
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    condition: template
    value_template: '{{ now().strftime("%H:%M") == states.input_select.lr_relax.state }}'
  action:
    service: scene.turn_on
    entity_id: scene.living_room_relax_transition

- id: living_room_time_to_die
  alias: Living Room Time to Dim
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    condition: template
    value_template: '{{ now().strftime("%H:%M") == states.input_select.lr_dim.state }}'
  action:
    service: scene.turn_on
    entity_id: scene.living_room_dimmed_transition

- id: living_room_nightlight_on
  alias: Living Room Nightlight On
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    condition: template
    value_template: '{{ now().strftime("%H:%M") == states.input_select.lr_nightlight.state }}'
  action: 
    service: scene.turn_on
    entity_id: scene.living_room_nightlight_transition

# Bedroom
- id: bedroom_wake_up
  alias: Bedroom Wake Up
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    condition: template
    value_template: '{{ now().strftime("%H:%M") == states.input_select.br_wake_up.state }}'
  action:
    service: scene.turn_on
    entity_id: scene.all_wake_up

- id: bedroom_light_on
  alias: Bedroom Light On
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    condition: template
    value_template: '{{ now().strftime("%H:%M") == states.input_select.br_light_on.state }}'
  action:
    service: scene.turn_on
    entity_id: scene.bedroom_dimmed

- id: bedroom_go_to_sleep
  alias: Bedroom Go to Sleep
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    condition: template
    value_template: '{{ now().strftime("%H:%M") == states.input_select.br_go_to_sleep.state }}'
  action:
    service: light.turn_off
    entity_id: light.nightstand

##########
# Input Select
##########

- id: playstation_input
  alias: Playstation Input
  trigger:
    platform: state
    entity_id: input_select.ps4_actions
  action: 
    - service_template: >
        {% if is_state("input_select.ps4_actions", "On") %}
          shell_command.ps4_on
        {%-elif is_state("input_select.ps4_actions", "Media Player") %}
          shell_command.ps4_media_player
        {%-elif is_state("input_select.ps4_actions", "Netflix") %}
          shell_command.ps4_netflix
        {%-elif is_state("input_select.ps4_actions", "Overwatch") %}
          shell_command.ps4_overwatch
        {%-elif is_state("input_select.ps4_actions", "Off") %}
          shell_command.ps4_off
        {% endif %}
    - service: input_select.select_option
      data:
        entity_id: input_select.ps4_actions
        option: "-"

- id: tv_actions_automation
  alias: TV Actions Automation
  trigger:
    platform: state
    entity_id: input_select.tv_actions
  action: 
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.tv_actions", "Power") %}
            script.tv_toggle_power
          {%-elif is_state("input_select.tv_actions", "Input Wii U") %}
            script.tv_input_wiiu
          {%-elif is_state("input_select.tv_actions", "Input Chromecast") %}
            script.tv_input_chromecast
          {%-elif is_state("input_select.tv_actions", "Input PS4") %}
            script.tv_input_ps4
          {%-elif is_state("input_select.tv_actions", "Input Misc") %}
            script.tv_input_misc
          {%-elif is_state("input_select.tv_actions", "Mute") %}
            script.tv_toggle_mute
          {%-elif is_state("input_select.tv_actions", "Volume +5") %}
            script.tv_volume_up
          {%-elif is_state("input_select.tv_actions", "Volume -5") %}
            script.tv_volume_down
          {% endif %}
    - service: input_select.select_option
      data:
        entity_id: input_select.tv_actions
        option: "-"
          



#- id: tv_bloom_and_tv
#  alias: bloom and tv
#  trigger:
#    platform: state
#    entity_id: light.tv_bloom
#  action:
#    service: homeassistant.toggle
#    entity_id: group.tv_group

#
# All

#- alias: Turn All Nightlights Off
#  trigger:
#    platform: sun
#    event: sunrise
#    offset: "+00:45:00"
#  action:
#    service: light.turn_off
#    entity_id: group.all_lights
#
#- alias: Energize Living Room at Sunrise
#  trigger:
#    platform: sun
#    event: sunrise
#  action:
#    service: scene.turn_on
#    entity_id: scene.living_room_energize
