##########
# Presence based
##########

- alias: Notify when tony phone changes location
  trigger: 
    platform: state
    entity_id: device_tracker.520dcd99cbb97b7d
  action:
    service: notify.pushover
    data_template:
      title: Tony Nexus 6 Location Changed
      message: >
        {{ trigger.from_state.state }} to {{ trigger.to_state.state }}

- alias: Turn on living room lights when sun sets and home
  trigger: 
    - platform: sun
      event: sunset
      offset: "-00:45:00"
    - platform: state
      entity_id: device_tracker.520dcd99cbb97b7d
      state: 'home'
  condition:
    - condition: state
      entity_id: device_tracker.520dcd99cbb97b7d
      state: 'home'
  action: 
    - service: scene.turn_on
      entity_id: scene.living_room_purple_accent
    
- alias: Turn off all lights when leaving home
  trigger:
    platform: state
    entity_id: device_tracker.520dcd99cbb97b7d
    state: 'not_home'
  condition:
    condition: state
    entity_id: device_tracker.520dcd99cbb97b7d
    state: 'not_home'
  action:
    - delay: 00:10:00
    - service: light.turn_off
      entity_id: group.all_lights

##########
# Time based
##########

# Living Room
- alias: Living Room Get Relaxed
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    condition: template
    value_template: '{{ now().strftime("%H:%M") == states.input_select.lr_relax.state }}'
  action:
    service: scene.turn_on
    entity_id: scene.living_room_relax_transition

- alias: Living Room Time to Dim
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    condition: template
    value_template: '{{ now().strftime("%H:%M") == states.input_select.lr_dim.state }}'
  action:
    service: scene.turn_on
    entity_id: scene.living_room_dimmed_transition

- alias: Living Room Nightlight On
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    condition: template
    value_template: '{{ now().strftime("%H:%M") == states.input_select.lr_nightlight.state }}'
  action: 
    service: scene.turn_on
    entity_id: scene.living_room_nightlight_transition

# Bedroom
- alias: Bedroom Wake Up
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    condition: template
    value_template: '{{ now().strftime("%H:%M") == states.input_select.br_wake_up.state }}'
  action:
    service: scene.turn_on
    entity_id: scene.all_wake_up

- alias: Bedroom Light On
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    condition: template
    value_template: '{{ now().strftime("%H:%M") == states.input_select.br_light_on.state }}'
  action:
    service: scene.turn_on
    entity_id: scene.bedroom_dimmed

- alias: Bedroom Go to Sleep
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    condition: template
    value_template: '{{ now().strftime("%H:%M") == states.input_select.br_go_to_sleep.state }}'
  action:
    service: light.turn_off
    entity_id: light.nightstand

# All

#- alias: Turn All Nightlights Off
#  trigger:
#    platform: sun
#    event: sunrise
#    offset: "+00:45:00"
#  action:
#    service: light.turn_off
#    entity_id: group.all_lights
#
#- alias: Energize Living Room at Sunrise
#  trigger:
#    platform: sun
#    event: sunrise
#  action:
#    service: scene.turn_on
#    entity_id: scene.living_room_energize
