alias: Turn off all lights when leaving home
trigger:
  platform: state
  entity_id: device_tracker.520dcd99cbb97b7d
  state: 'not_home'
condition:
  condition: state
  entity_id: device_tracker.520dcd99cbb97b7d
  state: 'not_home'
action:
  - delay: 00:05:00
  - service: light.turn_off
    entity_id: group.all_lights

