alias: Bedroom Light On
trigger:
  platform: time
  minutes: '/1'
  seconds: 0
condition:
  condition: template
  value_template: '{{ now().strftime("%H:%M") == states.input_select.br_light_on.state }}'
action:
  service: scene.turn_on
  entity_id: scene.bedroom_dimmed
