alias: All Wake Up
trigger:
  platform: time
  minutes: '/1'
  seconds: 0
condition:
  condition: template
  value_template: '{{ now().strftime("%H:%M") == states.input_select.br_wake_up.state }}'
action:
  service: scene.turn_on
  entity_id: scene.all_wake_up
