alias: Living Room Time to Dim
trigger:
  platform: time
  minutes: '/1'
  seconds: 0
condition:
  condition: template
  value_template: '{{ now().strftime("%H:%M") == states.input_select.lr_dim.state }}'
action:
  service: scene.turn_on
  entity_id: scene.living_room_dimmed_transition
